version: "3.9"
services:
  user_service:
    build: user_service/.
    depends_on:
      - db
    restart: always

  article_server:
    build: article_service/.
    ports:
      - "8080:8080"
    depends_on:
      - db
      - user_service
    restart: always

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]

  jaeger:
    image: jaegertracing/all-in-one:1
    ports:
      - "16686:16686"

  adminer:
    image: adminer
    ports:
      - "8081:8080"


